version: '3.8'
services:
  web:
    image: nginx
    ports:
    - "8080:80"
    
    volumes:
    - ./html:/usr/share/nginx/html

    # environment:
    #  - NGINX_HOST=foobar.com
    #  - NGINX_PORT=80


